print("leonardo")
print("Luis Manuel Lepe")
print("Bryan M.")
print("Carlos")
print("Edmundo Isaac")
print("Daniel Alcaraz")
print("Juan Pablo")
print("Juan José")
print("manuel")
print("Diego")
print("Sarah")
print("Osmar")
print("Martin")
print ("Brulio Perdomo")
print("Holaa. Estefania Gutierrez")
print ("Valeria Rojas")